# Generated by Django 6.0.8 on 2026-09-27 12:17

import apps.core.uploads
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicsession_course'),
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('department', 'Entire department'), ('level', 'A level'), ('course', 'A course'), ('space', 'A Space')], default='department', max_length=12)),
                ('target_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('resumption', 'Resumption'), ('exam', 'Exam'), ('test', 'Test'), ('assignment', 'Assignment due'), ('registration', 'Registration deadline'), ('event', 'Department event'), ('holiday', 'Holiday'), ('meeting', 'Meeting')], max_length=14)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.department')),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.course')),
                ('target_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='spaces.space')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['department', 'starts_at'], name='notices_aca_departm_c9a795_idx')],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('department', 'Entire department'), ('level', 'A level'), ('course', 'A course'), ('space', 'A Space')], default='department', max_length=12)),
                ('target_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=3000)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('attachment', models.FileField(blank=True, upload_to=apps.core.uploads.announcement_upload_path)),
                ('attachment_name', models.CharField(blank=True, max_length=150)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.department')),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.course')),
                ('target_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='spaces.space')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department', 'expires_at'], name='notices_ann_departm_c9abbd_idx')],
            },
        ),
    ]
