# Generated by Django 6.0.8 on 2026-09-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicsession_course'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='unique_unscoped_role',
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course reps: the course they represent (leave department empty)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='academics.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('user', 'role', 'course'), name='unique_course_role'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', True), ('department__isnull', True)), fields=('user', 'role'), name='unique_unscoped_role'),
        ),
    ]
