# Generated by Django 6.0.8 on 2026-09-28 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicsession_course'),
        ('accounts', '0003_user_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('hod', 'HOD'), ('lecturer', 'Lecturer'), ('level_adviser', 'Level Adviser'), ('exam_officer', 'Exam Officer')], max_length=16)),
                ('title', models.CharField(blank=True, choices=[('prof', 'Prof.'), ('dr', 'Dr.'), ('engr', 'Engr.'), ('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('', 'No title')], max_length=6)),
                ('staff_id', models.CharField(blank=True, help_text='Optional, helps the HOD verify you', max_length=30)),
                ('office', models.CharField(blank=True, max_length=120)),
                ('office_hours', models.CharField(blank=True, max_length=160)),
                ('requested_level', models.PositiveSmallIntegerField(blank=True, help_text='Level advisers', null=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for verification'), ('verified', 'Verified'), ('rejected', 'Not verified')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='Reason if not verified', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='unique_scoped_role',
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Level advisers: the level they advise (with the department)', null=True),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course reps and lecturers: the course (leave department empty)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('course_rep', 'Course Rep'), ('lecturer', 'Lecturer'), ('level_adviser', 'Level Adviser'), ('exam_officer', 'Exam Officer'), ('moderator', 'Moderator'), ('department_admin', 'Department Admin'), ('super_admin', 'Super Admin')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False), ('level__isnull', True)), fields=('user', 'role', 'department'), name='unique_scoped_role'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('level__isnull', False)), fields=('user', 'role', 'department', 'level'), name='unique_level_role'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='requested_courses',
            field=models.ManyToManyField(blank=True, help_text='Lecturers: courses they say they teach', related_name='+', to='academics.course'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['status'], name='accounts_st_status_363bce_idx'),
        ),
    ]
