# Generated by Django 6.0.8 on 2026-10-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_messages_from',
            field=models.CharField(choices=[('everyone', 'Anyone in my department'), ('following', 'Only people I follow'), ('nobody', 'Nobody')], default='everyone', max_length=10),
        ),
    ]
