# Generated by Django 6.0.8 on 2026-09-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicsession_course'),
        ('posts', '0002_comment_is_hidden_comment_removed_by_moderator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_ids', models.JSONField(default=list)),
                ('topic_ids', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.department')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveSmallIntegerField(default=3)),
                ('remind_on', models.DateField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['remind_on', 'sent_at'], name='discover_op_remind__93feb1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='one_reminder_per_opportunity')],
            },
        ),
    ]
