# Generated by Django 6.0.8 on 2026-09-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2025/2026', max_length=20)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.university')),
            ],
            options={
                'ordering': ['-name'],
                'constraints': [models.UniqueConstraint(fields=('university', 'name'), name='unique_session_name')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. CSC 301', max_length=12)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=40)),
                ('units', models.PositiveSmallIntegerField(default=3)),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')])),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'First semester'), (2, 'Second semester')])),
                ('lecturer', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department')),
            ],
            options={
                'ordering': ['level', 'code'],
                'indexes': [models.Index(fields=['department', 'level'], name='academics_c_departm_6e41f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'slug'), name='unique_course_slug'), models.UniqueConstraint(fields=('department', 'code'), name='unique_course_code')],
            },
        ),
    ]
