# Generated by Django 6.0.8 on 2026-09-27 12:17

import apps.core.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicsession_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('resource_type', models.CharField(choices=[('past_question', 'Past question'), ('lecture_note', 'Lecture note'), ('slides', 'Slides'), ('assignment', 'Assignment'), ('other', 'Other')], max_length=16)),
                ('exam_type', models.CharField(blank=True, choices=[('exam', 'Exam'), ('test', 'Test'), ('quiz', 'Quiz')], max_length=8)),
                ('semester', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First semester'), (2, 'Second semester')], null=True)),
                ('file', models.FileField(upload_to=apps.core.uploads.resource_upload_path)),
                ('original_name', models.CharField(max_length=150)),
                ('size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('is_verified_upload', models.BooleanField(default=False, help_text='Uploaded by a course rep or department admin')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.course')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='academics.academicsession')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course', 'resource_type'], name='resources_r_course__a09768_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-download_count'], name='resources_r_downloa_2d221e_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcedownload',
            constraint=models.UniqueConstraint(fields=('resource', 'user', 'day'), name='unique_daily_download'),
        ),
        migrations.AddConstraint(
            model_name='resourcerating',
            constraint=models.UniqueConstraint(fields=('resource', 'user'), name='unique_resource_rating'),
        ),
        migrations.AddConstraint(
            model_name='resourcerating',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='stars_1_to_5'),
        ),
    ]
