# Generated by Django 6.0.8 on 2026-09-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='index_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
