# Generated by Django 6.0.8 on 2026-09-27 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NexScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('upvote_received', 'Upvote received'), ('downvote_received', 'Downvote received'), ('answer_accepted', 'Answer accepted'), ('resource_rated', 'Resource rated 4+ stars'), ('resource_downloaded', 'Resource downloaded'), ('content_removed', 'Content removed by a moderator')], max_length=32)),
                ('amount', models.IntegerField()),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.PositiveBigIntegerField()),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nexscore_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='reputation__user_id_c6584a_idx'), models.Index(fields=['source_type', 'source_id'], name='reputation__source__611134_idx')],
            },
        ),
    ]
