# Generated by Django 6.0.8 on 2026-09-27 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicsession_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('dismiss', 'Dismissed reports'), ('remove', 'Removed content'), ('restore', 'Restored content'), ('auto_hide', 'Auto-hidden after reports'), ('suspend', 'Suspended user'), ('unsuspend', 'Lifted suspension'), ('ban', 'Banned user'), ('unban', 'Unbanned user'), ('reveal', 'Viewed anonymous author'), ('delete_space', 'Deleted Space')], max_length=14)),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('resource', 'Resource'), ('user', 'User'), ('space', 'Space')], max_length=10)),
                ('target_id', models.PositiveBigIntegerField()),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.department')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department', '-created_at'], name='moderation__departm_7640ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('resource', 'Resource'), ('user', 'User'), ('space', 'Space')], max_length=10)),
                ('target_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or bullying'), ('abuse', 'Abuse or threats'), ('inappropriate', 'Inappropriate content'), ('misleading', 'Misleading information'), ('copyright', 'Copyright concern'), ('other', 'Something else')], max_length=16)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('actioned', 'Action taken')], default='open', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.department')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department', 'status', '-created_at'], name='moderation__departm_a4b427_idx'), models.Index(fields=['target_type', 'target_id'], name='moderation__target__dc17d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'target_type', 'target_id'), name='one_report_per_target')],
            },
        ),
    ]
