# Generated by Django 6.0.8 on 2026-10-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='target_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('resource', 'Resource'), ('user', 'User'), ('space', 'Space'), ('message', 'Direct message')], max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('resource', 'Resource'), ('user', 'User'), ('space', 'Space'), ('message', 'Direct message')], max_length=10),
        ),
    ]
