# Generated by Django 6.0.8 on 2026-09-27 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicsession_course'),
        ('resources', '0002_resource_index_error_resource_indexed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('page', models.PositiveIntegerField(blank=True, help_text='PDF page or slide number', null=True)),
                ('text', models.TextField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='resources.resource')),
            ],
            options={
                'ordering': ['resource', 'position'],
                'indexes': [models.Index(fields=['resource', 'position'], name='nexai_resou_resourc_3713af_idx')],
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ask', 'Ask'), ('summary', 'Summary'), ('quiz', 'Quiz'), ('insights', 'Past question insights')], max_length=10)),
                ('used_model', models.BooleanField(default=False, help_text='False when answered from search only')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nexai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='nexai_usage_user_id_d52a61_idx')],
            },
        ),
    ]
