# Generated by Django 6.0.8 on 2026-09-27 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicsession_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('community', 'Community'), ('course', 'Course'), ('level', 'Level'), ('department', 'Department')], default='community', max_length=12)),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='For level Spaces', null=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('rules', models.TextField(blank=True, max_length=2000)),
                ('icon', models.CharField(blank=True, help_text='An emoji or short symbol', max_length=4)),
                ('is_official', models.BooleanField(default=False)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space', to='academics.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='academics.department')),
            ],
            options={
                'ordering': ['-is_official', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator')], default='member', max_length=10)),
                ('is_muted', models.BooleanField(default=False, help_text="Hide this Space's posts from my feeds")),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spaces.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('department', 'slug'), name='unique_space_slug'),
        ),
        migrations.AddIndex(
            model_name='spacemembership',
            index=models.Index(fields=['user', 'is_muted'], name='spaces_spac_user_id_5af747_idx'),
        ),
        migrations.AddConstraint(
            model_name='spacemembership',
            constraint=models.UniqueConstraint(fields=('space', 'user'), name='unique_space_membership'),
        ),
    ]
