# Generated by Django 6.0.8 on 2026-09-27 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def open_course_spaces(apps, schema_editor):
    Space = apps.get_model("spaces", "Space")
    Space.objects.filter(course__isnull=False).update(requires_approval=False)


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text="Members must be approved by the Space's managers before they can join"),
        ),
        migrations.CreateModel(
            name='SpaceJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='spaces.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['space', 'status'], name='spaces_spac_space_i_af0e0c_idx')],
                'constraints': [models.UniqueConstraint(fields=('space', 'user'), name='one_join_request_per_space')],
            },
        ),
        migrations.RunPython(open_course_spaces, migrations.RunPython.noop),
    ]
