# Generated by Django 6.0.8 on 2026-09-27 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicsession_course'),
        ('posts', '0001_initial'),
        ('spaces', '0001_initial'),
        ('topics', '0002_default_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='removed_by_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='removed_by_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='spaces.space'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['space', '-created_at'], name='posts_post_space_i_e70ae6_idx'),
        ),
    ]
