# Generated by Django 6.0.8 on 2026-10-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_is_hidden_comment_removed_by_moderator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Set when the author edits the post', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='repost_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='repost_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('post', 'Post'), ('question', 'Question'), ('poll', 'Poll'), ('event', 'Event'), ('opportunity', 'Opportunity'), ('repost', 'Repost')], default='post', max_length=12),
        ),
        migrations.CreateModel(
            name='CommentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='posts.comment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
