# Generated by Django 6.0.8 on 2026-09-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_in_app', models.BooleanField(default=True)),
                ('social_push', models.BooleanField(default=False)),
                ('academic_in_app', models.BooleanField(default=True)),
                ('academic_push', models.BooleanField(default=True)),
                ('department_in_app', models.BooleanField(default=True)),
                ('department_push', models.BooleanField(default=True)),
                ('opportunities_in_app', models.BooleanField(default=True)),
                ('opportunities_push', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=60)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('social', 'Social'), ('academic', 'Academic'), ('department', 'Department'), ('opportunities', 'Opportunities')], max_length=14)),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('mention', 'Mention'), ('follow', 'New follower'), ('votes', 'Upvote milestone'), ('accepted', 'Answer accepted'), ('resource', 'New course resource'), ('past_question', 'New past question'), ('event_reminder', 'Academic reminder'), ('announcement', 'Announcement'), ('opportunity', 'New opportunity'), ('opportunity_reminder', 'Deadline reminder'), ('study_group', 'Study group')], max_length=22)),
                ('text', models.CharField(max_length=240)),
                ('url', models.CharField(max_length=300)),
                ('is_critical', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('push_status', models.CharField(choices=[('none', 'Not sent'), ('pending', 'Waiting to send'), ('sent', 'Sent')], default='none', max_length=8)),
                ('dedupe_key', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['recipient', 'category', '-created_at'], name='notificatio_recipie_7b1202_idx'), models.Index(fields=['push_status'], name='notificatio_push_st_d62c89_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('recipient', 'dedupe_key'), name='unique_notification_dedupe')],
            },
        ),
    ]
