# Generated by Django 6.0.8 on 2026-09-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reply', 'Reply'), ('mention', 'Mention'), ('follow', 'New follower'), ('votes', 'Upvote milestone'), ('accepted', 'Answer accepted'), ('resource', 'New course resource'), ('past_question', 'New past question'), ('event_reminder', 'Academic reminder'), ('announcement', 'Announcement'), ('opportunity', 'New opportunity'), ('opportunity_reminder', 'Deadline reminder'), ('study_group', 'Study group'), ('space_request', 'Space join request')], max_length=22),
        ),
    ]
