# Generated by Django 6.0.8 on 2026-10-02 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='digest',
            field=models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly (Mondays)')], default='weekly', help_text='Summary email of what you missed', max_length=8),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='messages_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='messages_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('social', 'Social'), ('academic', 'Academic'), ('department', 'Department'), ('opportunities', 'Opportunities'), ('messages', 'Messages')], max_length=14),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reply', 'Reply'), ('mention', 'Mention'), ('follow', 'New follower'), ('votes', 'Upvote milestone'), ('accepted', 'Answer accepted'), ('resource', 'New course resource'), ('past_question', 'New past question'), ('event_reminder', 'Academic reminder'), ('announcement', 'Announcement'), ('opportunity', 'New opportunity'), ('opportunity_reminder', 'Deadline reminder'), ('study_group', 'Study group'), ('space_request', 'Space join request'), ('staff', 'Staff verification'), ('repost', 'Repost'), ('message', 'Direct message')], max_length=22),
        ),
        migrations.CreateModel(
            name='DigestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='e.g. "daily:2026-10-05" or "weekly:2026-W41"', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'period'), name='one_digest_per_period')],
            },
        ),
    ]
