# Generated by Django 6.0.8 on 2026-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationpreference_digest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestlog',
            name='emailed',
            field=models.BooleanField(default=True, help_text='False when there was nothing new to send'),
        ),
    ]
